# Generated by Django 4.2.1 on 2023-06-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('space_capacity', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_time', models.DateField(blank=True, null=True)),
                ('bookings', models.IntegerField(default=0)),
                ('slot_left', models.IntegerField(default=0)),
                ('is_cancelled', models.BooleanField(default=False)),
            ],
        ),
    ]
